allow nil values for consumer and credential
Kong/go-pdk pull request #153
Opened 2023-07-18 14:49 UTC by lvermeire

#152 

kong.client.authenticate should accept nil values for consumer and credential.

2023-07-18 14:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/go-pdk?pullRequest=153) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/go-pdk?pullRequest=153) before we can accept your contribution.<br/><hr/>**Loïc Vermeire** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/go-pdk?pullRequest=153) it.</sub>

2023-09-20 08:37 UTC, fffonion approved these changes

2023-09-20 08:37 UTC, fffonion commented
@lvermeire Thank you. Could you sign the CLA with the email that authors the commit please?

2023-09-25 07:17 UTC, lvermeire commented
> @lvermeire Thank you. Could you sign the CLA with the email that authors the commit please?

I believe I did? Originally signed the commit with the wrong email, but updated it right after with a force push.

2024-02-22 00:47 UTC, gszr requested changes
We need a test case here https://github.com/Kong/go-pdk/blob/master/client/client_test.go#L84

2024-02-22 09:36 UTC, lvermeire commented
> @lvermeire could you look into adding the test case? Thank you for your contribution!

Added two test cases.

2024-02-22 12:19 UTC, gszr approved these changes
@lvermeire Thank you for your contribution! 🙏🏻

2024-02-22 12:19 UTC, gszr commented on client/client.go
> +		return fmt.Errorf("either credential or consumer must be provided")
nice that you preserved the kong error message here : )

2024-02-22 12:41 UTC, merged

2024-02-22 12:43 UTC, gszr commented
@lvermeire - With this fix you are eligible for a "Kong contributor badge" since this is part of Kong Gateway; please fill out the form at https://docs.google.com/forms/d/e/1FAIpQLSfacQHac-PYIDIrDOi_W2l7cWxBDRIVBs6xE5HnlojPvdhL9g/viewform if you'd like to claim it! 🦍