fix(test): fix hanging by channel for kong.response.exit
Kong/go-pdk pull request #170
Opened 2024-01-18 04:07 UTC by jakeslee

Fix #169. 

Channel `stateChange` isn't buffered channel. The `e.Finish()` method writes the  channel, but the consumer is in the same go routine. So it causes a dead lock.

Change the channel to buffered can solve the issue.

2024-01-18 04:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/go-pdk?pullRequest=170) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/go-pdk?pullRequest=170) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/go-pdk?pullRequest=170) it.</sub>

2024-02-15 10:23 UTC, nowNick approved these changes

2024-02-15 10:25 UTC, nowNick commented
I think this is good to go, but @gszr could you take another look?

2024-02-20 12:29 UTC, gszr requested changes
@jakeslee - Thank you for the PR, we really appreciate it. Could you add a simple regression test case? Could be cased, for example, in the code sample posted in the referenced issue.

2024-02-21 15:30 UTC, winslowdibona commented
@gszr @nowNick I've added these changes as well as the requested test to my PR (#174) that addresses the hanging channel issue and adds support for shared ctx handlers in the test utility.

In the interest of getting this breaking change fixed could we look at moving forward with my PR? Would you rather I break the PR into two separate PRs (one for hanging channel issue, one for shared ctx handlers)?

I'm only persistent in bringing this up because in its current state, the testing utility does not work and prevents developers from moving forward with the tool.

2024-02-21 17:38 UTC, gszr commented
Closing this in favor of #174.

2024-02-21 17:38 UTC, closed without merging